### ISSUE TITLE
Behat + mink_zombie_driver error

### ISSUE THREAD

**Issue by bourg-ismael** [minkphp/MinkZombieDriver#118]
Hi,

I try to run a test with Behat + mink_zombie_driver and I have a Node error.

Here the result of my test with the error with different files of my project:
https://gist.github.com/bourg-ismael/059a249e8f28de4eecdb

**Comment by aik099** [comment]
Is this still an issue. Zombie has released 2 major versions since then.

**Comment by stof** [comment]
Closing as there has not been any feedback in years
