### ISSUE TITLE
PHP fatal error in context file leads to node process stucking

### ISSUE THREAD

**Issue by jazzfog** [minkphp/MinkZombieDriver#120]
I have such case: PHP fatal error in context (like attempt to click not existing button `$this->getSession()->getPage()->findButton('NotExisting')->click();`) leads to `Node` process stucking - repeated `Behat` start fails because `Node` can not reuse port which is already in use.

First start

```
# php ./composer/vendor/behat/behat/bin/behat

...[feature description skipped]...

PHP Fatal error:  Call to a member function click() on a non-object 
in /project/tests/behat/features/bootstrap/Search.php on line 17

Fatal error: Call to a member function click() on a non-object 
in /project/tests/behat/features/bootstrap/Search.php on line 17
```

Second start and further

```
# php ../../composer/vendor/behat/behat/bin/behat

...[feature description skipped]...

Server process has been terminated: (8) [
events.js:72
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
  at errnoException (net.js:904:11)
  at Server._listen2 (net.js:1042:14)
  at listen (net.js:1064:10)
  at net.js:1146:9
  at Object._onImmediate (/usr/lib/node_modules/zombie/lib/zombie/dns_mask.js:69:16)
  at processImmediate [as _immediateCallback] (timers.js:345:15)
] (RuntimeException)
```

So all my further calls will fail, and the only thing i can do here is to go to server, run `netstat -tulpn` and `kill <node PID>`.

Is there anything you can do about it?

**Comment by aik099** [comment]
In constructions like yours
```php
$this->getSession()->getPage()->findButton('NotExisting')->click();
```

When:
1. element is searched for
2. an action is immediately performed on element regardless of it's presence on a page (because all `find` methods returns `null`, when element is found)
we can't really foresee the error and react upfront.

Here are several options that you can use:
1. use `WebAssert` class, which throws an exception when element wasn't found
2. manually check for `null` after doing `find*` calls
3. use `pressButton` method instead of `findButton` and `click` method combination

**Comment by aik099** [comment]
> Is there anything you can do about it?

To my knowledge you can't catch fatal error using `set_error_handler` and send appropriate termination command to Zombie. And theoretically with PHP, which started Zombie server, dead the Zombie server should also die automatically.

**Comment by jazzfog** [comment]
> use pressButton method instead of findButton and click method combination

This is not the point, the point is fatal error hangs Zombie process and you have to go to server over ssh and kill process manually.

**Comment by aik099** [comment]
I got that eventually and posted 2nd comment as you can see. If you can arrange a PR with a fix or at least explain the fixing concept to me (if you have no experience with NodeJS stuff fixing), then I would be glad to help.

**Comment by jazzfog** [comment]
> To my knowledge you can't catch fatal error using set_error_handler and send appropriate termination command to Zombie. 

I believe you still can run some code using `shutdown functions`.

> And theoretically with PHP, which started Zombie server, dead the Zombie server should also die automatically.

It appears it does not stop Zombie.

**Comment by aik099** [comment]
> I believe you still can run some code using `shutdown functions`.

You're correct. Totally forgot about them. Then we can as part of `ZombieServer` class register a shutdown function, that will send JS command to Zombie NodeJS process to also fail/stop. Or we can just use Symfony Process object, that used to start that process to terminate the process :smile:

**Comment by jazzfog** [comment]
:high_five:

**Comment by aik099** [comment]
Then I'm waiting for PR to review.

Tricky thing would be writing unit test to verify that behavior, because fatal error would crash test suite. @stof , any ideas about that?

**Comment by aik099** [comment]
@jazzfog should I be awaiting PR from you?

**Comment by jazzfog** [comment]
Sorry, can't do :(

**Comment by aik099** [comment]
No time I presume.
