### ISSUE TITLE
Update Travis CI to use IO.JS for Zombie 4.x versions

### ISSUE THREAD

**Issue by aik099** [minkphp/MinkZombieDriver#133]
Recently Zombie 4.x was released, which requires IO.JS to run.

I propose to:

1. make node binary path, used in tests, configurable through ENV variable (right now it's hardcoded to `node`)
2. download the Linux version of IO.JS binary from https://iojs.org/en/index.html (have no idea how to determine latest IO.JS version to download)
3. use any PHP version with special ENV flag that, when present would:

* trigger IO.JS download
* zip archive extraction
* setting ENV variable with node binary to wherever extraction was made
* run the tests

In total we need to test each zombie version (2.x, 3.x, 4.x) on latest PHP version and latest zombie version on any PHP version.

**Comment by stof** [comment]
IMO, testing the node-compatible zombie version on all PHP version is easier than testing the latest (especially given that the latest version requires io.js), as it will avoid having many builds installing io.js

The zombie code will not change based on the php version anyway.

**Comment by stof** [comment]
Can you work on this before working on Zombie 4 fixes ? It would make it easier by seeing the result in Travis builds.

**Comment by aik099** [comment]
> Can you work on this before working on Zombie 4 fixes ? 

So what is plan of action here exactly:

1. use Zombie 3.x version with combination of any PHP (now we're using Zombie 4.x)
2. use Zombie 2.x version with combination of PHP 5.6 (as now)

?

**Comment by stof** [comment]
yeah, and use Zombie 4 in a single job using io.js rather than node (and PHP 5.6 as it is the maintained version of PHP)

**Comment by stof** [comment]
@aik099 when working on installing io.js, please try to find a way to do it without using sudo.
I have an idea to run the webserver for web fixtures without using sudo, which would allow us to switch to the docker-based infrastructure on driver repos requiring a webserver too. So it would be better to avoid having something else forcing us to keep using the old infrastructure.

**Comment by aik099** [comment]
OK.
