### ISSUE TITLE
Write about IO.JS version of Zombie in README

### ISSUE THREAD

**Issue by aik099** [minkphp/MinkZombieDriver#135]
We should note in README, that:

1. Zombie 4.x+ requires IO.JS to run instead of Node.JS
2. versions of Zombie > 4.x and < 4.0.12 doesn't support multi-part form submission

**Comment by stof** [comment]
IMO, we don't need to document that zombie 4 requires io.js. This is something zombie needs to document, not us (and maybe even enforce in npm if it is possible).

**Comment by stof** [comment]
OK, actually, we should document it, because of https://github.com/minkphp/MinkZombieDriver/pull/136#issuecomment-115565069

**Comment by stof** [comment]
btw, should it be in the readme, or in the docs repo ?

**Comment by aik099** [comment]
> OK, actually, we should document it, because of https://github.com/minkphp/MinkZombieDriver/pull/136#issuecomment-115565069

OK.

> btw, should it be in the readme, or in the docs repo ?

Yes, docs are fine too.

**Comment by stof** [comment]
Closing this as Zombie 4 now runs on node.js (4+) as io.js and node.js have been merged back.
