### ISSUE TITLE
The installation of Zombie 4 is broken

### ISSUE THREAD

**Issue by stof** [minkphp/MinkZombieDriver#149]
At that time, we used io.js, but its installation is now failing.

We should use node.js 4 (or 5) instead, to fix the installation.

**Comment by aik099** [comment]
That is really interesting, because Zombie repo homepage still saying that IO.JS must be used.

**Comment by aik099** [comment]
PR is created and ready for review.

The build failures:
1. every PHP version - because of cookie semicolon test
2. php 7 because https://github.com/minkphp/Mink/issues/684
