### ISSUE TITLE
Throw exception, when options are changed on running server

### ISSUE THREAD

**Issue by aik099** [minkphp/MinkZombieDriver#157]
The `Behat\Mink\Driver\NodeJS\Server` class have bunch of methods for setting options of the NodeJS server, that will be created. There is only one problem with them: when used on already running server they:

* have no effect
* developer thinks all worked fine

Proposing to throw an exception, when attempt to change running server options is made.

**Comment by stof** [comment]
looks good to me

**Comment by aik099** [comment]
Nice, will send a PR soon. Please look on other issues I've reported for Zombie.

**Comment by aik099** [comment]
PR created, ready for review.
