### ISSUE TITLE
Changing host or port should regenerate server code

### ISSUE THREAD

**Issue by aik099** [minkphp/MinkZombieDriver#158]
The `Behat\Mink\Driver\NodeJS\Server::createTemporaryServer` uses following options of the server:

* host
* port
* nodeModulesPath

Currently on change of `nodeModulesPath` causes temporary server code to be regenerated.

Propose to regenerate temporary server code also on `host` and `port` option change.

Separate issue (see #157) is created to prevent calling these methods on already running server, that would have no effect.

**Comment by stof** [comment]
See https://github.com/minkphp/MinkZombieDriver/issues/161 for my proposal to solve it in a much better way

**Comment by aik099** [comment]
Agreed that creating ENV-based server instead of PHP variable patching is better way.
