### ISSUE TITLE
Using "Behat\Mink\Driver\NodeJS\Server::createTemporaryServer" replaces user provided server code

### ISSUE THREAD

**Issue by aik099** [minkphp/MinkZombieDriver#160]
The `Behat\Mink\Driver\NodeJS\Server::createTemporaryServer` method would generate and replace existing server code with generated one. This is a problem for cases, when during server construction custom server path was provided.

Related issues:

* #157
* #158

**Comment by stof** [comment]
I don't understand what you mean here. This method is called only when no path is provided.

**Comment by stof** [comment]
Actually, I found another place calling this method, but it is now useless thanks to #162 so I'm fixing it.

**Comment by aik099** [comment]
I've meant this line: https://github.com/stof/MinkZombieDriver/blob/d0caf88e0812b79b268323c6fe29d8f898db9824/src/NodeJS/Server.php#L183

```php
$this->serverPath = $this->createTemporaryServer();
```

that is called from `setNodeModulesPath` method.

**Comment by aik099** [comment]
Then this is solved by #163.
