### ISSUE TITLE
How to change timeout?

### ISSUE THREAD

**Issue by chris-fa** [minkphp/MinkZombieDriver#175]
I'm getting `Error: Timeout: did not get to load all resources on this page` and apparently it's a timeout issue as per [this issue](https://github.com/assaf/zombie/issues/882) in Zombie repo.

I'm using Behat and MinkExtension but the docs doesn't explain how to change Zombie's `waitDuration`, how do I do this?

**Comment by stof** [comment]
currently, you cannot

**Comment by chris-fa** [comment]
Is there any type of workaround I could use in the meantime? Maybe changing options directly on zombie rather than mink extension?

**Comment by aik099** [comment]
There is an abandoned #154 PR, that once fixed would allow setting options of created Zombie process. My guess is that MinkExtension also needs to have a PR to allow specifying Zombie options.

**Comment by chris-fa** [comment]
Thanks, closing this
