### ISSUE TITLE
Driver does not work with Symfony 4.0+

### ISSUE THREAD

**Issue by Dragonrun1** [minkphp/MinkZombieDriver#187]
Your requirements could not be resolved to an installable set of packages.
...
    - Can only install one of: symfony/process[v3.4.20, v4.2.3].
    - Can only install one of: symfony/process[v3.4.21, v4.2.3].
    - Can only install one of: symfony/process[v3.4.22, v4.2.3].
...
    - Installation request for symfony/process (locked at v4.2.3) -> satisfiable by symfony/process[v4.2.3].

**Comment by aik099** [comment]
It's easy to fix. You can safely send PR, that update `symfony/process` component requirement to allow any `4.x` version of Symfony.

**Comment by beoboo** [comment]
I added this PR: #189
