### ISSUE TITLE
Kill running Node server on start

### ISSUE THREAD

**Issue by faceleg** [minkphp/MinkZombieDriver#19]
Provide an option to force `ZombieServer` to kill a running NodeJS server on `$server->start()`

This is required in cases where a script does not complete execution - on next run, as the NodeJS server hasn't been stopped, therefore Zombie Driver can't start another one.

``` PHP
$server = new ZombieServer('localhost', 8124, '/usr/bin/node', null, 2000000, '/usr/lib/node_modules/');
$driver = new ZombieDriver($server);
$this->session = new Session($driver);
$destroyExisting = true;
$this->session->start($destroyExisting); // Stop an existing server & start another
```

**Comment by jasonlfunk** [comment]
+1 I'm still running into this issue. Has a workaround been found?

**Comment by aik099** [comment]
I guess @faceleg have solved described problem 3 years ago, but forgot to mention the solution in here.

@jasonlfunk , do you have a reproducible test case? Also maybe NodeJS process hangs because problem described in #120 task.

**Comment by faceleg** [comment]
No way I can remember that far back. I doubt I did solve it else I would have reported back.

**Comment by jasonlfunk** [comment]
@aik099 Yep. #120 is exactly the problem I'm running into.

**Comment by aik099** [comment]
@jasonlfunk , then please create PR for that task according to explained idea.

**Comment by jasonlfunk** [comment]
I'll see what I can do. I was able to easily fix the problem inside my test class with this:

`register_shutdown_function(array(self::class, 'tearDown'));`

where the `tearDown` method class `stop` on the session.

**Comment by aik099** [comment]
The #125 should solve this problem by stopping Zombie process at the end of the script (even when PHP fatal error happened causing script to crash).
