### ISSUE TITLE
SinglePageApplication: Javascript is not executed

### ISSUE THREAD

**Issue by yajo10** [minkphp/MinkZombieDriver#201]
Hey, 
I'm trying to get Min working. With Chromium everything works quite fine. All JavaScript is executed on a single page application. 
I've installed zombie global and followed strictly the examples. However, it does not executes JavaScript automatically. 
Did I miss a setting or anything else in the workflow? 

       $driver = new \Behat\Mink\Driver\ZombieDriver(
            new \Behat\Mink\Driver\NodeJS\Server\ZombieServer()
        );
        $mink = new Mink(array(
            'zombie' => new \Behat\Mink\Session($driver),
            'browser' => new \Behat\Mink\Session(
                new ChromeDriver('http://localhost:9222', null, 'http://www.google.com')
            )
        ));
        $mink->setDefaultSessionName('zombie');

        $mink->getSession()->visit(env('WEB_URL')."/some-url/2a07e084-c49f-4900-9a6c-59570d987686");

        $page = $mink->getSession()->getPage();

        var_dump($page);
        print_r($page->getContent());

        $button = $page->findById('export');

        $button->click();

Executing with Zombie the page just the correct html and the script-includes, that should be executed. But that's not done. 
In Chrome the includes are working properly.
Any hints or needed additional information?

        "behat/mink": "^1.9",
        "behat/mink-selenium2-driver": "^1.5",
        "behat/mink-zombie-driver": "^1.5",

         zombie@6.1.4

Thanks in advance!

**Comment by aik099** [comment]
Does some simple JS page work for you, e.g. when you change page HTML via JS and then assert that in Mink?

**Comment by yajo10** [comment]
Thanks a lot for your reply. I'm sorry for bothering you! 

Just as a reference: I've asked the question again there: https://github.com/assaf/zombie/issues/1218
