### ISSUE TITLE
Doesn't work with newer versions of Node.

### ISSUE THREAD

**Issue by nathggns** [minkphp/MinkZombieDriver#42]
Newer versions of Node require local versions of packages regardless of if they're installed globally or not. This means that the `require('zombie')` call will always fail.

**Comment by Nikoms** [comment]
Hello,

I just want to answer to @nathggns (commented on Jul 26, 2013) because I had the  same "relative path" problem today and I found this topic :) To make it work, you can use variables like this:
```
            zombie:
                node_modules_path: %paths.base%/node_modules/
```

Cheers ;)
