### ISSUE TITLE
Ensure high code coverage (now: 77.08%)

### ISSUE THREAD

**Issue by aik099** [minkphp/MinkZombieDriver#51]
Main issue: https://github.com/minkphp/Mink/issues/406

Code Coverage: __77.08%__
![zombie_code_coverage](https://f.cloud.github.com/assets/1277526/1676385/7bf2d89a-5d18-11e3-8339-19415712e373.png)

**Comment by stof** [comment]
The coverage of the ZombieDriver class is now properly covered (mostly thanks to our enhancements in the driver testsuite). After #165, the remaining uncovered lines are about some error handling in case of Zombie triggering errors (for instance when clicking on links), which may be hard to trigger for real.

![zombie_driver_coverage](https://cloud.githubusercontent.com/assets/439401/13547248/62e1a9ea-e2cb-11e5-85f8-f49d0ac4e636.png)

Regarding the ``NodeJS`` subnamespace, most uncovered lines are either dumb getters or setters or error handling conditions (or the code in the ZombieServer class triggered when running it from inside a phar).
![zombie_server_coverage](https://cloud.githubusercontent.com/assets/439401/13547254/81becbae-e2cb-11e5-8efc-aad88c39dc41.png)

So I suggest closing it.

**Comment by aik099** [comment]
OK.
